title = "Cortex Config"

[models]
llm_repo = "Qwen/Qwen2.5-1.5B-Instruct-GGUF"
llm_filename = "qwen2.5-1.5b-instruct-q4_k_m.gguf"

[tracker]
directories = [
    "/home/rushil/Desktop/test/",
]

[logger]
logs_file_name = "logs"
logs_file_location = "."
print_logs = false
store_logs = true